name: Deploy with Dokploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Dokploy Deploy
        uses: dokploy/github-action@v1
        with:
          apiKey: ${{ secrets.DOKPLOY_API_KEY }}
