name: Deploy to Self-hosted Dokploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Dokploy on Self-hosted VPS
        run: |
          curl -X POST http://173.212.245.233:3000/api/deploy \
            -H "Authorization: Bearer ${{ secrets.DOKPLOY_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "appId": "tu_app_id"
            }'
