name: Deploy to Dokploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Dokploy Deployment
        run: |
          curl -X POST https://api.dokploy.com/v1/deploy \
            -H "Authorization: Bearer ${{ secrets.DOKPLOY_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "appId": "tu_app_id"
            }'
